baseURL: https://sanjayprofile.netlify.app
title: Sanjay Portfolio
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 2
    - identifier: about
      name: About
      url: /about/
      weight: 3
params:
  author: Sanjay Hamal
  description: Sanjay Hamal - Data analyst / programmer
  menu_item_separator: ' - '
  social:
    - icon: github
      name: Github
      url: http://sanjayhamal.com.np/
